(function () {
  "use strict";
  const e = React.createElement;
  const { useEffect, useMemo, useState } = React;

  const projects = [
    ["parquet-tool", "after", "TypeScript · C++ · Node.js", "不依賴既有 npm Parquet 套件，實作讀寫、追加、合併、驗證與多種格式轉換的資料工具。", "https://github.com/Lian0123/parquet-tool", true],
    ["scribeva-editor-react", "after", "React · Editor", "將文字編輯能力整合進 React 應用，探索元件化介面、狀態管理與編輯體驗。", "https://github.com/Lian0123/scribeva-editor-react", true],
    ["scribeva-editor", "after", "Editor Core · JavaScript", "文字編輯器核心專案，聚焦內容編輯、操作行為與可延伸的編輯基礎。", "https://github.com/Lian0123/scribeva-editor", true],
    ["expense-tracker-app", "after", "Application · Data", "以日常收支為情境的完整應用，整合資料輸入、整理與瀏覽流程。", "https://github.com/Lian0123/expense-tracker-app"],
    ["virtual-business-card-project", "after", "Web App · PWA", "建立與展示數位名片的網頁工具，兼顧多語內容、客製化與行動裝置使用。", "https://github.com/Lian0123/virtual-business-card-project"],
    ["camera-simulator", "after", "Simulation · Web", "以網頁重現相機操作概念，將攝影參數轉化為可操作的模擬體驗。", "https://github.com/Lian0123/camera-simulator"],
    ["auto-generator-package-diagram-uml", "after", "Automation · UML", "自動整理套件關係並產生 UML 圖，降低理解專案結構與維護文件的成本。", "https://github.com/Lian0123/auto-generator-package-diagram-uml"],
    ["jp-travel-talk-tool", "after", "Language · Utility", "面向日本旅遊情境的會話輔助工具，讓常用語句更容易查找與使用。", "https://github.com/Lian0123/jp-travel-talk-tool"],
    ["my-typescript-express-template", "after", "TypeScript · Express", "將常用後端結構整理成可重用模板，縮短 Node.js API 專案初始化流程。", "https://github.com/Lian0123/my-typescript-express-template"],
    ["HardwaveFuzzyProjectWebVersion", "university", "Web · Fuzzy Control", "專題的網頁版本，將模糊控制成果轉化為可由瀏覽器接觸的展示介面。", "https://github.com/Lian0123/HardwaveFuzzyProjectWebVersion", false, true],
    ["HardwaveFuzzyProject", "university", "Hardware · Fuzzy Control", "大學專題核心實作，結合硬體與模糊控制方法完成研究型作品。", "https://github.com/Lian0123/HardwaveFuzzyProject", false, true],
    ["twcall", "university", "Linux · Shell", "處理終端機 Big5 顯示情境的工具，回應台灣 Linux 使用者的在地需求。", "https://github.com/Lian0123/twcall"],
    ["TextArt", "university", "Text Processing", "以文字與視覺呈現為主題，探索字元輸出與圖像表現。", "https://github.com/Lian0123/TextArt"],
    ["UnknownClang", "university", "C · Compiler", "從 C 語言與編譯概念出發的實驗型專案，呈現對語言底層的探索。", "https://github.com/Lian0123/UnknownClang"],
    ["FMiCa-TW.sh", "university", "Linux · Bash", "為台灣使用者整理 Linux Mint Cinnamon 安裝與環境設定的自動化腳本。", "http://fmica-tw.sh"]
  ].map(x => ({ title:x[0], stage:x[1], tech:x[2], description:x[3], link:x[4], featured:!!x[5], thesis:!!x[6] }));

  const writings = [
    ["iOS SandBox Account 與 Apple Pay 的踩坑筆記", "after", "iOS · Apple Pay", "整理 Sandbox 帳號、Apple Pay 測試流程與 iCloud error 34608 的實務排查經驗。", "https://medium.com/@lian000123/ios-sandbox-account-%E8%88%87-apple-pay%E7%9A%84%E8%B8%A9%E5%9D%91%E7%AD%86%E8%A8%98-%E5%90%AB-icloud-error-34608%E5%95%8F%E9%A1%8C-f7de82aa3a40?postPublishedType=initial"],
    ["Vibe Coding 開發導入 AI 問題筆記（一）— 為什麼 AI 會偷懶", "after", "AI · Engineering", "從開發協作角度分析 AI 產出縮水、跳步或逃避複雜工作的原因。", "https://medium.com/@lian000123/vibe-coding-%E9%96%8B%E7%99%BC%E5%B0%8E%E5%85%A5ai%E5%95%8F%E9%A1%8C%E7%AD%86%E8%A8%98-%E4%B8%80-%E7%82%BA%E4%BB%80%E9%BA%BCai%E6%9C%83%E5%81%B7%E6%87%B6-934a70def12f"],
    ["Vibe Coding 開發導入 AI 問題筆記（零）— 為什麼要寫這篇文章", "after", "AI · Engineering", "說明導入 AI 開發後值得記錄的落差、問題意識與系列文章脈絡。", "https://medium.com/@lian000123/vibe-coding-%E9%96%8B%E7%99%BC%E5%B0%8E%E5%85%A5ai%E5%95%8F%E9%A1%8C%E7%AD%86%E8%A8%98-%E9%9B%B6-%E7%82%BA%E4%BB%80%E9%BA%BC%E8%A6%81%E5%AF%AB%E9%80%99%E7%AF%87%E6%96%87%E7%AB%A0-1b48d516f61d"],
    ["基於替換密碼的音訊轉置 BMP 影像欺騙偽造設計與實作", "university", "DSP · Security", "結合古典替換密碼、音訊與 BMP 影像轉置的設計研究。", "https://www.slideshare.net/slideshow/imageaudioplayer-1072-dsp-148791863/148791863"],
    ["FML Tool 理論說明", "university", "Fuzzy Logic", "整理模糊邏輯工具的理論背景與實作概念。", "https://www.slideshare.net/slideshow/fml-tool/141286121"],
    ["Linux 安裝篇 ArchLabs 2019.01.20 — Part 3", "university", "Linux · ArchLabs", "ArchLabs 安裝系列第三部分。", "https://www.slideshare.net/slideshow/linux-linux-archlabs-20190120-part3/129864461"],
    ["Linux 安裝篇 ArchLabs 2019.01.20 — Part 2", "university", "Linux · ArchLabs", "ArchLabs 安裝系列第二部分。", "https://www.slideshare.net/slideshow/linux-linux-archlabs-20190120-part2/129864001"],
    ["Linux 安裝篇 ArchLabs 2019.01.20 — Part 1", "university", "Linux · ArchLabs", "ArchLabs 安裝系列第一部分。", "https://www.slideshare.net/slideshow/linux-linux-archlabs-20190120-part1/129863580"],
    ["Linux 推坑教學：FMiCa-tw.sh 說明文件", "university", "Linux · Bash", "FMiCa-TW.sh 的使用方式與設計說明。", "http://fmica-tw.sh"],
    ["C 語言從崩潰到崩潰 Ex（二）", "university", "C Language", "延續基礎內容的 C 語言實作教材。", "https://www.slideshare.net/slideshow/cex-79080568/79080568"],
    ["在手機上使用 Linux", "university", "Linux · Mobile", "介紹在行動裝置上使用 Linux 環境的方法。", "https://www.slideshare.net/slideshow/linux-linux-77271842/77271842"],
    ["Linux Mint Cinnamon 18.1 操作設定教學", "university", "Linux Mint", "桌面環境操作與系統設定入門。", "https://www.slideshare.net/slideshow/linux-linux-mint-cinnamon-181/74049170"],
    ["C 語言從崩潰到崩潰 Ex（一）", "university", "C Language", "以實例整理 C 語言基礎觀念。", "https://www.slideshare.net/slideshow/cex-70564975/70564975"],
    ["Linux CLI 基本教學", "university", "Linux · CLI", "終端指令與命令列工具的基礎教材。", "https://www.slideshare.net/slideshow/linux-linux-cli/69541869"],
    ["Linux 安裝篇：Manjaro Linux 201606 KDE", "university", "Linux · Manjaro", "Manjaro KDE 的安裝與環境設定流程。", "https://www.slideshare.net/slideshow/linux-manjaro-linux-201606-kde/67209576"],
    ["Linux 安裝篇：Linux Mint 18 Cinnamon", "university", "Linux Mint", "Linux Mint 18 Cinnamon 安裝流程。", "https://www.slideshare.net/slideshow/linux-linux-mint-18-cinnamon-66499815/66499815"],
    ["何謂 Linux？", "university", "Linux", "從基本概念介紹 Linux 與開源系統。", "https://www.slideshare.net/slideshow/linux-linux-66243857/66243857"],
    ["C 語言從崩潰到崩潰", "university", "C Language", "C 語言入門系列的起點。", "https://www.slideshare.net/slideshow/c-66240731/66240731"]
  ].map(x => ({ title:x[0], stage:x[1], tech:x[2], description:x[3], link:x[4] }));

  const otherWorks = [
    ["using-inkscape-and-blender-make-2d-animation-book", "service", "Inkscape · Blender", "記錄以 Inkscape 與 Blender 製作 2D 動畫的完整實作與踩坑經驗。", "https://github.com/Lian0123/using-inkscape-and-blender-make-2d-animation-book"],
    ["新式外來人口統一證號換發介紹｜政策動畫", "service", "Animation · Communication", "以動畫協助傳達新式統一證號換發政策，將複雜資訊轉化為易理解內容。", "https://youtube.com/watch?v=Q0_8md_3VdA"],
    ["Lian-Free-PPT-Template", "university", "Presentation Design", "可自由使用的簡報範本，整理視覺層級與內容版型。", "https://github.com/Lian0123/Lian-Free-PPT-Template"]
  ].map(x => ({ title:x[0], stage:x[1], tech:x[2], description:x[3], link:x[4] }));

  const i18n = {
    zh: { labels:{ after:"工作後 Side Project", university:"大學作品", service:"服役時作品" }, nav:["關於","作品","工程著作","其他創作","連結"], kicker:"BACKEND · FULL-STACK · TOOL MAKING", name:"連永立 · lian0123", heroTitle:"把複雜問題，整理成能長期使用的工具。", heroText:"作品從 Node.js 與原生擴充、文字編輯器，到生活工具與技術教材。關注的不只是完成，也包含可維護性、使用情境與知識傳遞。", view:"瀏覽作品", contact:"聯絡我", aboutTitle:"一條從系統底層走向產品體驗的實作路徑", aboutText:"早期作品聚焦 Linux、C 語言、訊號處理與模糊控制；工作後延伸到 TypeScript、React、資料格式、編輯器與實用型產品。這些作品共同呈現：能理解底層、能完成產品，也能把經驗整理成別人看得懂的內容。", selected:"代表作品", selectedText:"優先呈現最能代表目前工程方向的專案。", cardTitle:"個人名片", cardText:"直接在頁面中預覽個人名片與 QR 聯絡名片。", engineering:"工程開發", engineeringText:"依創作階段整理的公開專案與可操作作品。", writing:"工程著作", writingText:"從近期實務踩坑與 AI 協作反思，到大學時期的 Linux、C 語言與研究成果。", other:"非工程創作", otherText:"技術之外，也把工具運用在動畫製作、政策溝通與簡報設計。", links:"繼續了解", linksText:"查看原始碼、長文與完整簡報。", viewProject:"查看專案", viewWork:"查看作品", openCard:"開啟名片", filter:["全部","工作後","大學"], stats:["工程專案","工程著作","持續創作年數"], footer:"依公開專案與著作重新整理" },
    en: { labels:{ after:"After work", university:"University", service:"Service work" }, nav:["About","Projects","Writing","Other work","Links"], kicker:"BACKEND · FULL-STACK · TOOL MAKING", name:"Lian Yong-Li · lian0123", heroTitle:"Turning complex problems into tools built to last.", heroText:"My work spans Node.js and native addons, editors, practical products, and technical learning materials—with an emphasis on maintainability, real use cases, and sharing knowledge.", view:"Explore work", contact:"Contact", aboutTitle:"A hands-on path from systems to product experience", aboutText:"Early projects explored Linux, C, signal processing, and fuzzy control. Recent work extends into TypeScript, React, data formats, editors, and practical products—showing systems thinking, product delivery, and technical communication.", selected:"Selected work", selectedText:"Projects that best represent my current engineering direction.", cardTitle:"Contact cards", cardText:"Preview the professional card and QR contact card directly on this page.", engineering:"Engineering projects", engineeringText:"Public projects grouped by the stage in which they were created.", writing:"Technical writing", writingText:"Recent field notes and AI collaboration reflections, plus earlier Linux, C, and research materials.", other:"Other creative work", otherText:"Using technical tools for animation, public communication, and presentation design.", links:"Find out more", linksText:"Browse source code, long-form writing, and presentations.", viewProject:"View project", viewWork:"View work", openCard:"Open card", filter:["All","After work","University"], stats:["Engineering projects","Technical works","Years creating"], footer:"Portfolio refreshed from public projects and publications" },
    jp: { labels:{ after:"社会人 Side Project", university:"大学作品", service:"兵役中の作品" }, nav:["概要","開発作品","技術記事","その他","リンク"], kicker:"BACKEND · FULL-STACK · TOOL MAKING", name:"連永立 · lian0123", heroTitle:"複雑な課題を、長く使えるツールへ。", heroText:"Node.jsとネイティブ拡張、エディター、実用ツール、技術教材まで、保守性・利用場面・知識共有を意識して公開制作を続けています。", view:"作品を見る", contact:"連絡する", aboutTitle:"システム基盤からプロダクト体験へ続く実践", aboutText:"初期はLinux、C言語、信号処理、ファジィ制御に取り組み、近年はTypeScript、React、データ形式、エディター、実用プロダクトへ展開しています。基盤理解、製品実装、技術共有を一つの軸で示します。", selected:"代表作品", selectedText:"現在の開発方向を最もよく示すプロジェクト。", cardTitle:"プロフィール名刺", cardText:"プロフィール名刺とQR連絡先をページ内で確認できます。", engineering:"開発作品", engineeringText:"制作時期ごとに整理した公開プロジェクト。", writing:"技術著作", writingText:"実務の知見、AI協働の考察、Linux・C言語・研究資料。", other:"その他の創作", otherText:"アニメーション、政策広報、プレゼンテーションデザインへの応用。", links:"さらに見る", linksText:"ソースコード、記事、スライドを公開しています。", viewProject:"プロジェクトを見る", viewWork:"作品を見る", openCard:"名刺を開く", filter:["すべて","社会人","大学"], stats:["開発プロジェクト","技術著作","制作年数"], footer:"公開プロジェクトと著作をもとに更新" }
  };
  const labels = i18n.zh.labels;
  const projectDates = { "parquet-tool":"2026-03-10", "scribeva-editor-react":"2026-07-19", "scribeva-editor":"2026-07-18", "expense-tracker-app":"2026-08-31", "virtual-business-card-project":"2026-02-15", "camera-simulator":"2026-02-28", "auto-generator-package-diagram-uml":"2026-03-09", "jp-travel-talk-tool":"2022-11-21", "my-typescript-express-template":"2022-01-05", "lian0123.github.io":"2020-04-24", "HardwaveFuzzyProjectWebVersion":"2019-11-22", "HardwaveFuzzyProject":"2019-07-12", "twcall":"2018-08-16", "TextArt":"2018-07-28", "UnknownClang":"2018-09-12", "FMiCa-TW.sh":"2017-07-27" };
  const writingDates = { "iOS SandBox Account 與 Apple Pay 的踩坑筆記":"2026-02-18", "Vibe Coding 開發導入 AI 問題筆記（一）— 為什麼 AI 會偷懶":"2026-02-17", "Vibe Coding 開發導入 AI 問題筆記（零）— 為什麼要寫這篇文章":"2026-02-16", "基於替換密碼的音訊轉置 BMP 影像欺騙偽造設計與實作":"2019-06-11", "FML Tool 理論說明":"2019-05-01", "Linux 安裝篇 ArchLabs 2019.01.20 — Part 3":"2019-01-30", "Linux 安裝篇 ArchLabs 2019.01.20 — Part 2":"2019-01-20", "Linux 安裝篇 ArchLabs 2019.01.20 — Part 1":"2019-01-10", "Linux 推坑教學：FMiCa-tw.sh 說明文件":"2018-07-01", "C 語言從崩潰到崩潰 Ex（二）":"2017-08-23", "在手機上使用 Linux":"2017-06-26", "Linux Mint Cinnamon 18.1 操作設定教學":"2017-04-08", "C 語言從崩潰到崩潰 Ex（一）":"2016-12-31", "Linux CLI 基本教學":"2016-11-26", "Linux 安裝篇：Manjaro Linux 201606 KDE":"2016-10-15", "Linux 安裝篇：Linux Mint 18 Cinnamon":"2016-09-01", "何謂 Linux？":"2016-08-15", "C 語言從崩潰到崩潰":"2016-07-15" };
  projects.forEach(item => { item.date = projectDates[item.title] || "2019-01-01"; });
  writings.forEach(item => { item.date = writingDates[item.title] || "2019-01-01"; });
  const otherDates = { "using-inkscape-and-blender-make-2d-animation-book":"2020-11-18", "新式外來人口統一證號換發介紹｜政策動畫":"2020-01-15", "Lian-Free-PPT-Template":"2019-07-27" };
  otherWorks.forEach(item => { item.date = otherDates[item.title] || "2019-01-01"; });
  projects.sort((a, b) => b.date.localeCompare(a.date));
  writings.sort((a, b) => b.date.localeCompare(a.date));
  writings.forEach(item => { item.tech = item.date + " · " + item.tech; });
  const links = [["GitHub", "程式碼與開源專案", "https://github.com/Lian0123"], ["Medium", "近期工程文章", "https://medium.com/@lian000123"], ["SlideShare", "技術教材與研究簡報", "https://www.slideshare.net/ssuser6090c0"], ["Zenn", "日文技術內容", "https://zenn.dev/lian0123"], ["DEV Community", "開發者社群文章", "https://dev.to/lian0123"], ["X", "社群動態", "https://x.com/lian000123"], ["Facebook", "社群頁面", "https://www.facebook.com/profile.php?id=100003135147006"], ["Pixiv", "視覺創作", "https://www.pixiv.net/users/14175602"]];

  const workCopy = {
    en: {
      "parquet-tool":["Parquet processing toolkit","A TypeScript and C++ native-addon toolkit for reading, writing, validating, merging, and converting Parquet data."], "scribeva-editor-react":["scribeva-editor-react","A React integration for text editing, component composition, state management, and editing experience."], "scribeva-editor":["scribeva-editor","An editor core focused on content operations, interaction behavior, and an extensible editing foundation."], "expense-tracker-app":["expense-tracker-app","A practical expense application that connects data entry, organization, and browsing into one product flow."], "virtual-business-card-project":["virtual-business-card-project","A web tool for creating and presenting digital business cards with customization and mobile support."], "camera-simulator":["camera-simulator","A browser-based camera simulation that turns photographic controls into an interactive experience."], "auto-generator-package-diagram-uml":["auto-generator-package-diagram-uml","An automation tool that maps package relationships and generates UML diagrams for easier maintenance."], "jp-travel-talk-tool":["jp-travel-talk-tool","A travel conversation helper that makes common Japanese phrases easier to find and use."], "my-typescript-express-template":["my-typescript-express-template","A reusable TypeScript and Express backend template that shortens Node.js API setup."], "lian0123.github.io":["lian0123.github.io","An evolving portfolio that brings together themes, PWA support, and a public project index."], "HardwaveFuzzyProjectWebVersion":["HardwaveFuzzyProjectWebVersion","The web version of a fuzzy-control capstone, making the research accessible through a browser."], "HardwaveFuzzyProject":["HardwaveFuzzyProject","A university capstone combining hardware and fuzzy-control methods."], "twcall":["twcall","A terminal tool for Big5 display issues and a better Linux experience for Taiwan users."], "TextArt":["TextArt","A programming experiment exploring character output and visual expression through text."], "UnknownClang":["UnknownClang","An experimental project exploring C language internals and compiler concepts."], "FMiCa-TW.sh":["FMiCa-TW.sh","An automated Linux Mint Cinnamon installation and environment setup script for Taiwan users."],
      "iOS SandBox Account 與 Apple Pay 的踩坑筆記":["iOS Sandbox Accounts and Apple Pay: Lessons Learned","Practical notes on Sandbox accounts, Apple Pay testing, and troubleshooting iCloud error 34608."], "Vibe Coding 開發導入 AI 問題筆記（一）— 為什麼 AI 會偷懶":["Vibe Coding with AI (1): Why AI Takes Shortcuts","An engineering view of why AI-assisted development may skip steps or avoid complex work."], "Vibe Coding 開發導入 AI 問題筆記（零）— 為什麼要寫這篇文章":["Vibe Coding with AI (0): Why Write This Series","The context and problem framing behind documenting AI-assisted development."], "基於替換密碼的音訊轉置 BMP 影像欺騙偽造設計與實作":["Audio-to-BMP Deceptive Encryption Design","A research design combining substitution ciphers, audio, and BMP image transposition."], "FML Tool 理論說明":["FML Tool: Theory","The theoretical background and implementation concepts behind a fuzzy-logic tool."], "Linux 推坑教學：FMiCa-tw.sh 說明文件":["FMiCa-tw.sh Linux Guide","Usage and design notes for the FMiCa-TW.sh environment script."], "using-inkscape-and-blender-make-2d-animation-book":["Making 2D Animation with Inkscape and Blender","A practical record of creating 2D animation with Inkscape and Blender."], "新式外來人口統一證號換發介紹｜政策動畫":["New Foreign Resident ID: Policy Animation","An animation that explains the new foreign resident ID replacement policy."], "Lian-Free-PPT-Template":["Lian-Free-PPT-Template","A freely reusable presentation template organized around visual hierarchy and content layouts."]
    },
    jp: {
      "parquet-tool":["Parquet処理ツール","TypeScriptとC++ネイティブアドオンで、Parquetの読み書き・検証・結合・変換を扱うツール。"], "scribeva-editor-react":["scribeva-editor-react","テキスト編集をReactへ統合し、コンポーネント構成と状態管理を試すプロジェクト。"], "scribeva-editor":["scribeva-editor","コンテンツ操作と拡張可能な編集基盤に焦点を当てたエディターコア。"], "expense-tracker-app":["expense-tracker-app","日々の支出入力・整理・閲覧を一つの流れにまとめた実用アプリ。"], "virtual-business-card-project":["virtual-business-card-project","カスタマイズとモバイル利用に対応したデジタル名刺作成Webツール。"], "camera-simulator":["camera-simulator","カメラ操作の概念をブラウザ上で体験できるシミュレーター。"], "auto-generator-package-diagram-uml":["auto-generator-package-diagram-uml","パッケージ関係を整理し、保守に役立つUML図を自動生成するツール。"], "jp-travel-talk-tool":["jp-travel-talk-tool","旅行で使う日本語フレーズを検索・利用しやすくする会話補助ツール。"], "my-typescript-express-template":["my-typescript-express-template","Node.js API開発の初期構成を短縮するTypeScript・Expressテンプレート。"], "lian0123.github.io":["lian0123.github.io","テーマ、PWA、公開作品一覧を統合した更新型ポートフォリオ。"], "HardwaveFuzzyProjectWebVersion":["HardwaveFuzzyProjectWebVersion","ファジィ制御研究をブラウザで確認できるようにした卒業制作のWeb版。"], "HardwaveFuzzyProject":["HardwaveFuzzyProject","ハードウェアとファジィ制御を組み合わせた大学卒業制作。"], "twcall":["twcall","台湾のLinux利用者向けにBig5表示問題を扱う端末ツール。"], "TextArt":["TextArt","文字出力と視覚表現を試すプログラミング実験。"], "UnknownClang":["UnknownClang","C言語とコンパイラー概念を探る実験的プロジェクト。"], "FMiCa-TW.sh":["FMiCa-TW.sh","台湾向けLinux Mint Cinnamon環境を自動構築するスクリプト。"],
      "iOS SandBox Account 與 Apple Pay 的踩坑筆記":["iOS Sandbox AccountとApple Payの記録","Sandbox、Apple Payテスト、iCloud error 34608の実務メモ。"], "Vibe Coding 開發導入 AI 問題筆記（一）— 為什麼 AI 會偷懶":["Vibe CodingとAI (1)：AIが手を抜く理由","AI支援開発で手順を省略したり複雑な作業を避ける理由を考察。"], "Vibe Coding 開發導入 AI 問題筆記（零）— 為什麼要寫這篇文章":["Vibe CodingとAI (0)：なぜ書くのか","AI支援開発を記録する背景と問題意識。"], "基於替換密碼的音訊轉置 BMP 影像欺騙偽造設計與實作":["音声のBMP転置暗号設計","置換暗号、音声、BMP画像転置を組み合わせた研究。"], "FML Tool 理論說明":["FML Tool理論","ファジィ論理ツールの理論背景と実装概念。"], "Linux 推坑教學：FMiCa-tw.sh 說明文件":["FMiCa-tw.sh Linux解説","FMiCa-TW.shの使い方と設計説明。"], "using-inkscape-and-blender-make-2d-animation-book":["InkscapeとBlenderで2Dアニメーション","InkscapeとBlenderによる2Dアニメーション制作記録。"], "新式外來人口統一證號換發介紹｜政策動畫":["新しい外国人統一番号：政策アニメ","新しい外国人番号の交換政策を説明するアニメーション。"], "Lian-Free-PPT-Template":["Lian-Free-PPT-Template","視覚階層とレイアウトを整理した自由利用可能なプレゼンテンプレート。"]
    }
  };
  function workText(item, language) { const translated = workCopy[language] && workCopy[language][item.title]; return translated ? { title:translated[0], description:translated[1] } : { title:item.title, description:item.description }; }
  Object.assign(workCopy.en, {
    "Linux 安裝篇 ArchLabs 2019.01.20 — Part 3":["Linux Install: ArchLabs Part 3","Post-install configuration and setup recommendations for ArchLabs."], "Linux 安裝篇 ArchLabs 2019.01.20 — Part 2":["Linux Install: ArchLabs Part 2","The second part of the ArchLabs installation series."], "Linux 安裝篇 ArchLabs 2019.01.20 — Part 1":["Linux Install: ArchLabs Part 1","The first part of the ArchLabs installation series."], "C 語言從崩潰到崩潰 Ex（二）":["C Language Crash to Crash Ex (2)","Practical C language material continuing the fundamentals series."], "在手機上使用 Linux":["Using Linux on a Phone","An introduction to running a Linux environment on a mobile device."], "Linux Mint Cinnamon 18.1 操作設定教學":["Linux Mint Cinnamon 18.1 Setup","An introduction to desktop operation and system configuration."], "C 語言從崩潰到崩潰 Ex（一）":["C Language Crash to Crash Ex (1)","C language fundamentals explained through practical examples."], "Linux CLI 基本教學":["Linux CLI Basics","Fundamentals of terminal commands and command-line tools."], "Linux 安裝篇：Manjaro Linux 201606 KDE":["Manjaro Linux 201606 KDE","Installation and environment setup for Manjaro KDE."], "Linux 安裝篇：Linux Mint 18 Cinnamon":["Linux Mint 18 Cinnamon","The installation process for Linux Mint 18 Cinnamon."], "何謂 Linux？":["What is Linux?","An introduction to Linux and open-source systems."], "C 語言從崩潰到崩潰":["C Language Crash to Crash","The starting point of the C language learning series."]
  });
  Object.assign(workCopy.jp, {
    "Linux 安裝篇 ArchLabs 2019.01.20 — Part 3":["Linux導入：ArchLabs Part 3","ArchLabs導入後の設定と推奨事項。"], "Linux 安裝篇 ArchLabs 2019.01.20 — Part 2":["Linux導入：ArchLabs Part 2","ArchLabs導入シリーズの第2部。"], "Linux 安裝篇 ArchLabs 2019.01.20 — Part 1":["Linux導入：ArchLabs Part 1","ArchLabs導入シリーズの第1部。"], "C 語言從崩潰到崩潰 Ex（二）":["C言語クラッシュからクラッシュ Ex (2)","C言語実践教材シリーズの続編。"], "在手機上使用 Linux":["スマートフォンでLinuxを使う","モバイル端末でLinux環境を使う方法。"], "Linux Mint Cinnamon 18.1 操作設定教學":["Linux Mint Cinnamon 18.1設定","デスクトップ操作とシステム設定の入門。"], "C 語言從崩潰到崩潰 Ex（一）":["C言語クラッシュからクラッシュ Ex (1)","実例で学ぶC言語の基礎。"], "Linux CLI 基本教學":["Linux CLI基本","端末コマンドとコマンドラインツールの基礎。"], "Linux 安裝篇：Manjaro Linux 201606 KDE":["Manjaro Linux 201606 KDE","Manjaro KDEの導入と環境設定。"], "Linux 安裝篇：Linux Mint 18 Cinnamon":["Linux Mint 18 Cinnamon","Linux Mint 18 Cinnamonの導入手順。"], "何謂 Linux？":["Linuxとは？","Linuxとオープンソースシステムの基本。"], "C 語言從崩潰到崩潰":["C言語クラッシュからクラッシュ","C言語入門シリーズの出発点。"]
  });
  const pillarCopy = {
    zh:[["資料與後端工程","以 TypeScript、Node.js 與 C++ Native Addon 實作資料工具與可重用的服務基礎。"],["編輯器與產品實作","從核心編輯器到 React 介面，持續處理狀態、互動與產品化問題。"],["跨領域技術溝通","將 Linux、C 語言、AI 導入與多媒體經驗整理成文章與教材。"]],
    en:[["Data & backend engineering","Reusable data tools and service foundations built with TypeScript, Node.js, and C++ native addons."],["Editors & product work","From editor cores to React interfaces, with attention to state, interaction, and product delivery."],["Cross-domain communication","Linux, C, AI-assisted development, and multimedia experience organized into practical material."]],
    jp:[["データ・バックエンド","TypeScript、Node.js、C++ネイティブアドオンによるデータツールと再利用可能な基盤。"],["エディター・プロダクト","編集コアからReact UIまで、状態・操作・製品化を継続的に実装。"],["分野横断の技術共有","Linux、C言語、AI導入、マルチメディアの経験を教材として整理。"]]
  };
  const linkCopy = {
    zh:[["程式碼與開源專案"],["近期工程文章"],["技術教材與研究簡報"],["日文技術內容"],["開發者社群文章"],["社群動態"],["社群頁面"],["視覺創作"]],
    en:[["Source code and open projects"],["Recent engineering writing"],["Technical slides and research"],["Japanese technical content"],["Developer community posts"],["Social updates"],["Social profile"],["Visual work"]],
    jp:[["ソースコードと公開プロジェクト"],["最近の技術記事"],["技術教材と研究スライド"],["日本語の技術コンテンツ"],["開発者コミュニティの記事"],["ソーシャル更新"],["ソーシャルプロフィール"],["ビジュアル作品"]]
  };

  function Card({ item, action, t, language }) {
    const localized = workText(item, language);
    return e("article", { className:"work-card" },
      e("div", { className:"work-card-top" }, e("span", { className:"stage-badge" }, t.labels[item.stage]), e("span", { className:"tech-label" }, item.tech)),
      e("div", { className:"work-date" }, item.date), e("h3", null, localized.title), e("p", null, localized.description),
      item.thesis ? e("span", { className:"thesis-label" }, "專題") : null,
      e("a", { href:item.link, target:"_blank", rel:"noopener noreferrer", className:"work-link" }, action+" ↗")
    );
  }

  function Heading(kicker, title, text) {
    return e("header", { className:"section-heading" }, e("p", { className:"eyebrow" }, kicker), e("h2", null, title), e("p", null, text));
  }

  function initParticles() {
    if (typeof window.particlesJS !== "function") return;
    window.particlesJS("particles-js", { particles: { number: { value: window.innerWidth < 740 ? 20 : 42, density: { enable: true, value_area: 900 } }, color: { value: "#44c98c" }, shape: { type: "circle" }, opacity: { value: .3, random: true }, size: { value: 3, random: true }, line_linked: { enable: true, distance: 140, color: "#2b9f72", opacity: .2, width: 1 }, move: { enable: !window.matchMedia("(prefers-reduced-motion: reduce)").matches, speed: .8 } }, interactivity: { detect_on: "canvas", events: { onhover: { enable: true, mode: "grab" }, onclick: { enable: true, mode: "push" }, resize: true }, modes: { grab: { distance: 160, line_linked: { opacity: .3 } }, push: { particles_nb: 3 } } }, retina_detect: true });
  }

  function App() {
    const [theme, setTheme] = useState(localStorage.getItem("site-theme") || "dark");
    const [language, setLanguage] = useState(localStorage.getItem("site-lang") || "zh");
    const [filter, setFilter] = useState("all");
    const [menuOpen, setMenuOpen] = useState(false);
    const t = i18n[language] || i18n.zh;
    writings.forEach(item => { if (!item.sourceTitle) item.sourceTitle = item.title; if (!item.sourceDescription) item.sourceDescription = item.description; const localized = workText({ ...item, title:item.sourceTitle, description:item.sourceDescription }, language); item.title = localized.title; item.description = localized.description; });
    links.forEach((item, index) => { if (!item.sourceDescription) item.sourceDescription = item[1]; item[1] = linkCopy[language][index] ? linkCopy[language][index][0] : item.sourceDescription; });
    const filtered = useMemo(() => filter === "all" ? projects : projects.filter(x => x.stage === filter), [filter]);
    useEffect(() => { document.body.dataset.theme = theme; localStorage.setItem("site-theme", theme); }, [theme]);
    useEffect(() => { document.documentElement.lang = language === "jp" ? "ja" : language === "en" ? "en" : "zh-Hant-TW"; localStorage.setItem("site-lang", language); }, [language]);
    useEffect(() => { const timer = window.setTimeout(initParticles, 0); return () => window.clearTimeout(timer); }, []);
    const scroll = id => document.getElementById(id).scrollIntoView({ behavior:"smooth" });
    return e("div", { className:"site" },
      e("header", { className:"topbar" }, e("div", { className:"topbar-inner" }, e("a", { className:"brand", href:"#top" }, "LIAN / 0123"), e("nav", { id:"site-navigation", className:menuOpen ? "mobile-nav is-open" : "mobile-nav", "aria-label":"主要導覽" }, e("ul", { className:"nav-list" }, [["about",t.nav[0]],["projects",t.nav[1]],["writing",t.nav[2]],["other",t.nav[3]],["links",t.nav[4]]].map(x=>e("li", {key:x[0]}, e("a", {className:"nav-link",href:"#"+x[0],onClick:()=>setMenuOpen(false)},x[1]))))), e("select", { className:"language-select", value:language, onChange:event=>setLanguage(event.target.value), "aria-label":"Language" }, e("option", {value:"zh"}, "繁中"), e("option", {value:"en"}, "EN"), e("option", {value:"jp"}, "日本語")), e("button", { className:"mobile-menu-toggle", onClick:()=>setMenuOpen(!menuOpen), "aria-expanded":menuOpen, "aria-controls":"site-navigation", "aria-label":menuOpen ? "關閉選單" : "開啟選單" }, menuOpen ? "✕" : "☰"), e("button", { className:"theme-toggle", onClick:()=>setTheme(theme === "dark" ? "light" : "dark"), "aria-label":"切換明暗主題" }, theme === "dark" ? "☀" : "◐"))),
      e("main", { id:"content" },
        e("section", { id:"top", className:"portfolio-hero" }, e("div", { className:"hero-copy" }, e("p", { className:"eyebrow" }, t.kicker), e("p", { className:"hero-name" }, t.name), e("h1", null, t.heroTitle), e("p", { className:"hero-summary" }, t.heroText), e("div", { className:"hero-actions" }, e("button", { className:"btn btn-primary", onClick:()=>scroll("projects") }, t.view), e("a", { className:"btn btn-secondary", href:"mailto:lian0123@hi2.in" }, t.contact))), e("div", { className:"hero-ledger" }, [[projects.length,t.stats[0]],[writings.length,t.stats[1]],[new Date().getFullYear()-2015+"+",t.stats[2]]].map((x,i)=>e("div", {className:"ledger-row",key:i},e("strong",null,x[0]),e("span",null,x[1]))))),
        e("section", { id:"about", className:"content-section about-section" }, Heading("01 / PROFILE", t.aboutTitle, t.aboutText), e("div", { className:"pillar-grid" }, pillarCopy[language].map((x,i)=>e("article", {key:x[0]},e("span",null,"0"+(i+1)),e("h3",null,x[0]),e("p",null,x[1]))))),
        e("section", { className:"content-section featured-section" }, Heading("02 / SELECTED", t.selected, t.selectedText), e("div", { className:"featured-work-grid" }, projects.filter(x=>x.featured).map(x=>e(Card,{key:x.title,item:x,action:t.viewProject,t:t,language:language})))),
        e("section", { className:"content-section business-card-section" }, Heading("03 / CONTACT CARD", t.cardTitle, t.cardText), e("div", { className:"business-card-grid" }, [["Lian0123_main_card.html",language === "en" ? "Professional card" : language === "jp" ? "プロフィール名刺" : "專業名片"],["Lian0123_qr_card.html",language === "en" ? "QR contact card" : language === "jp" ? "QR連絡先" : "QR 聯絡名片"]].map(x=>e("article", { className:"business-card-item", key:x[0] }, e("h3", null, x[1]), e("div", { className:"business-card-preview" }, e("iframe", { src:"./"+x[0], title:x[1], loading:"lazy", referrerPolicy:"no-referrer" })), e("a", { className:"work-link", href:"./"+x[0], target:"_blank", rel:"noopener noreferrer" }, t.openCard+" ↗"))))),
        e("section", { id:"projects", className:"content-section" }, Heading("04 / ENGINEERING", t.engineering, t.engineeringText), e("div", { className:"filter-row" }, [["all",t.filter[0]],["after",t.filter[1]],["university",t.filter[2]]].map(x=>e("button",{key:x[0],className:"filter-button"+(filter===x[0]?" active":""),onClick:()=>setFilter(x[0])},x[1]))), e("div", { className:"work-grid" }, filtered.map(x=>e(Card,{key:x.title,item:x,action:t.viewProject,t:t,language:language})))),
        e("section", { id:"writing", className:"content-section" }, Heading("05 / WRITING", t.writing, t.writingText), e("div", { className:"writing-list" }, writings.map((x,i)=>e("a",{className:"writing-item",key:x.title,href:x.link,target:"_blank",rel:"noopener noreferrer"},e("span",{className:"writing-index"},String(i+1).padStart(2,"0")),e("div",null,e("p",{className:"writing-meta"},x.date+" · "+t.labels[x.stage]+" · "+x.tech.replace(x.date+" · ","")),e("h3",null,x.title),e("p",null,x.description)),e("span",{className:"writing-arrow"},"↗"))))) ,
        e("section", { id:"other", className:"content-section" }, Heading("06 / OTHER WORK", t.other, t.otherText), e("div", { className:"work-grid other-grid" }, otherWorks.map(x=>e(Card,{key:x.title,item:x,action:t.viewWork,t:t,language:language})))),
        e("section", { id:"links", className:"content-section links-section" }, Heading("07 / LINKS", t.links, t.linksText), e("div", { className:"link-grid" }, links.map(x=>e("a",{key:x[0],href:x[2],target:"_blank",rel:"noopener noreferrer"},e("strong",null,x[0]),e("span",null,x[1]),e("b",null,"↗")))))
      ),
      e("footer",null,e("span",null,"© "+new Date().getFullYear()+" lian0123"),e("span",null,t.footer))
    );
  }
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", () => navigator.serviceWorker.register("./service-worker.js").catch(() => null));
  }
  ReactDOM.createRoot(document.getElementById("root")).render(e(App));
})();
