
const documentView = new Vue({
    el:"#documentView", 
    data:{
    },
    mounted() {
        this.$i18n.locale = 'zh-tw';
    },
    methods:{

    },
    i18n:new VueI18n({
        locale: 'zh-tw',
        fallbackLocale: 'zh-tw',
        messages:{
            "zh-tw": {
                slideType:`教學文`,
                about:`介紹`,
                slideView:[
                    {
                        titleText : `看似比較簡單的Linux推坑教學 Linux安裝篇 ArchLabs 2019.01.20安裝 Part1`,
                        writeDate : `2019-01-30`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/iJdTREnXCdcRuM`,
                        mainText  : `ArchLabs Linux安裝教學的第一篇，此篇對於ArchLabs Linux進行簡單的說明，並介紹如何配置VirtualBox VM。`,
                        linksTag  : `linux-linux-archlabs-20190120-part1`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part1`,
                    },
                    {
                        titleText : `看似比較簡單的Linux推坑教學 Linux安裝篇 ArchLabs 2019.01.20安裝 Part2`,
                        writeDate : `2019-01-30`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/x2VRc210Hzl9OQ`,
                        mainText  : `ArchLabs Linux安裝教學的第二篇，此篇對於ArchLabs Linux安裝流程進行了詳細的說明與註解。`,
                        linksTag  : `linux-linux-archlabs-20190120-part2`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part2`,
                    },
                    {
                        titleText : `看似比較簡單的Linux推坑教學 Linux安裝篇 ArchLabs 2019.01.20安裝 Part3`,
                        writeDate : `2019-01-30`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/7Ofn6klzwdRpQp`,
                        mainText  : `ArchLabs Linux安裝教學的第三篇，此篇對於ArchLabs Linux安裝完後，建議要進行的設定。`,
                        linksTag  : `linux-linux-archlabs-20190120-part3`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part3`
                    },
                    {
                        titleText : `看似比較簡單的Linux推坑教學 Linux安裝篇 manjaro linux 201606 kde`,
                        writeDate : `2016-10-15`,
                        version   : `v0.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/n6UjJXGJe9nAuJ`,
                        mainText  : `此篇為早期所寫，針對於Manjaro Linux系統在VirtualBox上的安裝與簡單設定。`,
                        linksTag  : `linux-manjaro-linux-201606-kde`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-manjaro-linux-201606-kde`,
                    },
                    {
                        titleText : `看似比較簡單的Linux推坑教學 linux mint cinnamon 18.1 操作設定教學`,
                        writeDate : `2017-04-08`,
                        version   : `v0.0.1`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/yhpyXyUr4WEo1x`,
                        mainText  : `此篇為針對於Linux Mint Cinnamon安裝完後，針對於Cinnamon設定功能的詳細解說。`,
                        linksTag  : `linux-linux-mint-cinnamon-181`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-mint-cinnamon-181`,
                    },
                    {
                        titleText : `看似比較簡單的Linux推坑教學 Linux CLI 基本教學`,
                        writeDate : `2016-11-26`,
                        version   : `v0.0.3`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/iFW3qCxyy2ioQo`,
                        mainText  : `此篇為針對於簡單的linux終端指令進行說明的初階教學文，其中對於常用的操作指令、w3m瀏覽器、vim做了簡單的說明。`,
                        linksTag  : `linux-linux-cli`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-cli`,
                    },
                    {
                        titleText : `看似比較簡單的推坑教學 C語言從崩潰到崩潰Ex(一)`,
                        writeDate : `2016-12-31`,
                        version   : `v1.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/8dHHHpQHqyPaQG`,
                        mainText  : `本文章為筆者早期寫C語言從崩潰到崩潰的重製版本，其重製目的為讓學弟妹們，能由ISO 9899的制定的C語言規格進行了解，並針對於基本的C語言語法做出說明。`,
                        linksTag  : `cex-70564975`,
                        links     : `https://www.slideshare.net/ssuser6090c0/cex-70564975`,
                    },
                    {
                        titleText : `看似比較簡單的推坑教學 C語言從崩潰到崩潰Ex(二)`,
                        writeDate : `2017-08-23`,
                        version   : `v1.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/k2M84AlR73oWhP`,
                        mainText  : `本文章為筆者早期寫C語言從崩潰到崩潰的重製版本，其重製目的為讓學弟妹們，能由ISO 9899的制定的C語言規格進行了解，在此對於進階C語言語法做出簡單說明。`,
                        linksTag  : `cex-79080568`,
                        links     : `https://www.slideshare.net/ssuser6090c0/cex-79080568`,
                    },
                    {
                        titleText : `FML Tool 理論說明`,
                        writeDate : `2019-04-12`,
                        version   : `v1.4.6`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/gEuQPhd79jVHYl`,
                        mainText  : `Fuzzy Markup Language介紹用的簡報。在此針對於對此FML推論做簡單介紹與國立臺南大學提供的FML Lite (OASE)工具中與其基因算法的逆向理論分析。`,
                        linksTag  : `fml-tool`,
                        links     : `https://www.slideshare.net/ssuser6090c0/fml-tool`,
                    },
                    {
                        titleText : `看似比較簡單的Linux推坑教學 講解在手機上使用 linux`,
                        writeDate : `2017-06-26`,
                        version   : `v0.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/McYYXljYqB1HIB`,
                        mainText  : `在此針對於Android上的GNUroot Debian軟體，去寫一篇中文的使用體驗與操作說明。`,
                        linksTag  : `linux-linux-77271842`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-77271842`,
                    },
                ]
            },
            "zh-cn": {
                slideType:`教学文`,
                about:`介绍`,
                slideView:[
                    {
                        titleText : `看似比较简单的Linux推坑教学 Linux安装篇 ArchLabs 2019.01.20安装 Part1`,
                        writeDate : `2019-01-30`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/iJdTREnXCdcRuM`,
                        mainText  : `ArchLabs Linux安装教学的第一篇，此篇对于ArchLabs Linux进行简单的说明，并介绍如何配置VirtualBox VM。`,
                        linksTag  : `linux-linux-archlabs-20190120-part1`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part1`,
                    },
                    {
                        titleText : `看似比较简单的Linux推坑教学 Linux安装篇 ArchLabs 2019.01.20安装 Part2`,
                        writeDate : `2019-01-30`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/x2VRc210Hzl9OQ`,
                        mainText  : `ArchLabs Linux安装教学的第二篇，此篇对于ArchLabs Linux安装流程进行了详细的说明与注解。`,
                        linksTag  : `linux-linux-archlabs-20190120-part2`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part2`,
                    },
                    {
                        titleText :`看似比较简单的Linux推坑教学 Linux安装篇 ArchLabs 2019.01.20安装 Part3`,
                        writeDate :`2019-01-30`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/7Ofn6klzwdRpQp`,
                        mainText  : `ArchLabs Linux安装教学的第三篇，此篇对于ArchLabs Linux安装完后，建议要进行的设定。`,
                        linksTag  : `linux-linux-archlabs-20190120-part3`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part3`,
                    },
                    {
                        titleText : `看似比较简单的Linux推坑教学 Linux安装篇 manjaro linux 201606 kde`,
                        writeDate : `2016-10-15`,
                        version   : `v0.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/n6UjJXGJe9nAuJ`,
                        mainText  : `此篇为早期所写，针对于Manjaro Linux系统在VirtualBox上的安装与简单设定。`,
                        linksTag  : `linux-manjaro-linux-201606-kde`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-manjaro-linux-201606-kde`,
                    },
                    {
                        titleText : `看似比较简单的Linux推坑教学 linux mint cinnamon 18.1 操作设定教学`,
                        writeDate : `2017-04-08`,
                        version   : `v0.0.1`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/yhpyXyUr4WEo1x`,
                        mainText  : `此篇为针对于Linux Mint Cinnamon安装完后，针对于Cinnamon设定功能的详细解说。`,
                        linksTag  : `linux-linux-mint-cinnamon-181`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-mint-cinnamon-181`,
                    },
                    {
                        titleText : `看似比较简单的Linux推坑教学 Linux CLI 基本教学`,
                        writeDate : `2016-11-26`,
                        version   : `v0.0.3`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/iFW3qCxyy2ioQo`,
                        mainText  : `此篇为针对于简单的linux终端指令进行说明的初阶教学文，其中对于常用的操作指令、w3m浏览器、vim做了简单的说明。`,
                        linksTag  : `linux-linux-cli`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-cli`,
                    },
                    {
                        titleText : `看似比较简单的推坑教学 C语言从崩溃到崩溃Ex(一)`,
                        writeDate : `2016-12-31`,
                        version   : `v1.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/8dHHHpQHqyPaQG`,
                        mainText  : `本文章为笔者早期写C语言从崩溃到崩溃的重制版本，其重制目的为让学弟妹们，能由ISO 9899的制定的C语言规格进行了解，并针对于基本的C语言语法做出说明。`,
                        linksTag  : `cex-70564975`,
                        links     : `https://www.slideshare.net/ssuser6090c0/cex-70564975`,
                    },
                    {
                        titleText : `看似比较简单的推坑教学 C语言从崩溃到崩溃Ex(二)`,
                        writeDate : `2017-08-23`,
                        version   : `v1.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/k2M84AlR73oWhP`,
                        mainText  : `本文章为笔者早期写C语言从崩溃到崩溃的重制版本，其重制目的为让学弟妹们，能由ISO 9899的制定的C语言规格进行了解，在此对于进阶C语言语法做出简单说明。`,
                        linksTag  : `cex-79080568`,
                        links     : `https://www.slideshare.net/ssuser6090c0/cex-79080568`,
                    },
                    {
                        titleText : `FML Tool 理论说明`,
                        writeDate : `2019-04-12`,
                        version   : `v1.4.6`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/gEuQPhd79jVHYl`,
                        mainText  : `Fuzzy Markup Language介绍用的简报。在此针对于对此FML推论做简单介绍与国立台南大学提供的FML Lite (OASE)工具中与其基因算法的逆向理论分析。`,
                        linksTag  : `fml-tool`,
                        links     : `https://www.slideshare.net/ssuser6090c0/fml-tool`,
                    },
                    {
                        titleText : `看似比较简单的Linux推坑教学 讲解在手机上使用 linux`,
                        writeDate : `2017-06-26`,
                        version   : `v0.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/McYYXljYqB1HIB`,
                        mainText  : `在此针对于Android上的GNUroot Debian软体，去写一篇中文的使用体验与操作说明。`,
                        linksTag  : `linux-linux-77271842`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-77271842`,
                    },
                ]
            },
            "en": {
                slideType:`Teaching`,
                about:`Introduction`,
                slideView:[
                    {
                        titleText : `See maybe simple Linux teaching Linux installation chapter, ArchLabs 2019.01.20 install part1`,
                        writeDate : `2019-01-30`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/iJdTREnXCdcRuM`,
                        mainText  : `The part 1 of ArchLabs Linux install, there give a simple explanation of ArchLabs Linux, and talk how to config in VirtualBox VM.`,
                        linksTag  : `linux-linux-archlabs-20190120-part1`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part1`,
                    },
                    {
                        titleText : `See maybe simple Linux teaching Linux installation chapter, ArchLabs 2019.01.20 install part2`,
                        writeDate : `2019-01-30`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/x2VRc210Hzl9OQ`,
                        mainText  : `The part 2 of ArchLabs Linux install, there give about install detail in any install step.`,
                        linksTag  : `linux-linux-archlabs-20190120-part2`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part2`,
                    },
                    {
                        titleText : `See maybe simple Linux teaching Linux installation chapter, ArchLabs 2019.01.20 install part3`,
                        writeDate : `2019-01-30`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/7Ofn6klzwdRpQp`,
                        mainText  : `The part 3 of ArchLabs Linux install, there give a some setting after ArchLabs Linux install.`,
                        linksTag  : `linux-linux-archlabs-20190120-part3`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part3`
                    },
                    {
                        titleText : `See maybe simple Linux teaching Linux installation chapter, manjaro linux 201606 kde`,
                        writeDate : `2016-10-15`,
                        version   : `v0.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/n6UjJXGJe9nAuJ`,
                        mainText  : `This article was written in some years before, there write about Manjaro Linux system install and easy setting with VirtualBox.`,
                        linksTag  : `linux-manjaro-linux-201606-kde`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-manjaro-linux-201606-kde`,
                    },
                    {
                        titleText : `See maybe simple Linux teaching Linux installation chapter, linux mint cinnamon 18.1 Setting`,
                        writeDate : `2017-04-08`,
                        version   : `v0.0.1`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/yhpyXyUr4WEo1x`,
                        mainText  : `This article is said about with after Linux Mint Cinnamon install, for Cinnamon setting detailed explanation.`,
                        linksTag  : `linux-linux-mint-cinnamon-181`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-mint-cinnamon-181`,
                    },
                    {
                        titleText : `See maybe simple Linux teaching, Linux CLI Basic`,
                        writeDate : `2016-11-26`,
                        version   : `v0.0.3`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/iFW3qCxyy2ioQo`,
                        mainText  : `This article is said about with linux terminal basic commands, and make a explanation of: basic control commands, w3m browser, vim.`,
                        linksTag  : `linux-linux-cli`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-cli`,
                    },
                    {
                        titleText : `See maybe simple teaching, C language from crazy to crazy EX (1)`,
                        writeDate : `2016-12-31`,
                        version   : `v1.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/8dHHHpQHqyPaQG`,
                        mainText  : `This article was written in some years before,it is rewrite for CS posterity that can konw ISO9899 standard, and C language basic format.`,
                        linksTag  : `cex-70564975`,
                        links     : `https://www.slideshare.net/ssuser6090c0/cex-70564975`,
                    },
                    {
                        titleText : `See maybe simple teaching, C language from crazy to crazy EX (2)`,
                        writeDate : `2017-08-23`,
                        version   : `v1.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/k2M84AlR73oWhP`,
                        mainText  : `This article was written in some years before,it is rewrite for CS posterity that can konw ISO9899 standard, and C language advanced format.`,
                        linksTag  : `cex-79080568`,
                        links     : `https://www.slideshare.net/ssuser6090c0/cex-79080568`,
                    },
                    {
                        titleText : `FML Tool Theory `,
                        writeDate : `2019-04-12`,
                        version   : `v1.4.6`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/gEuQPhd79jVHYl`,
                        mainText  : `This is presentation for Fuzzy Markup Language, a brief introdction for FML inference with National Tainan University FML Lite (OASE) Tool and analysis of reverse genetic algorithm.`,
                        linksTag  : `fml-tool`,
                        links     : `https://www.slideshare.net/ssuser6090c0/fml-tool`,
                    },
                    {
                        titleText : `See maybe simple teaching, How to using linux(debian) in android phone`,
                        writeDate : `2017-06-26`,
                        version   : `v0.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/McYYXljYqB1HIB`,
                        mainText  : `For the GNUroot Debian software on Android, and write a chinese explain and operation instructions.`,
                        linksTag  : `linux-linux-77271842`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-77271842`,
                    },
                ]
            },
            "jp": {
                slideType:`教学`,
                about:`紹介`,
                slideView:[
                    {
                        titleText : `一見シンプルなLinux教学 Linuxインストール ArchLabs 2019.01.20インストール(1)`,
                        writeDate : `平成31年1月30日`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/iJdTREnXCdcRuM`,
                        mainText  : `ArchLabs Linux インストール教学 Part1，この記事ではArchLabs Linuxの簡単な説明とVirtualBox VMの構成方法について説明します。`,
                        linksTag  : `linux-linux-archlabs-20190120-part1`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part1`,
                    },
                    {
                        titleText : `一見シンプルなLinux教学 Linuxインストール ArchLabs 2019.01.20インストール(2)`,
                        writeDate : `平成31年1月30日`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/x2VRc210Hzl9OQ`,
                        mainText  : `ArchLabs Linux インストール教学 Part2，の記事ではArchLabs Linuxのインストール。`,
                        linksTag  : `linux-linux-archlabs-20190120-part2`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part2`,
                    },
                    {
                        titleText : `一見シンプルなLinux教学 Linuxインストール ArchLabs 2019.01.20インストール(3)`,
                        writeDate : `平成31年1月30日`,
                        version   : `v0.0.2`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/7Ofn6klzwdRpQp`,
                        mainText  : `ArchLabs Linux インストール教学 Part3，の記事ではArchLabs Linuxのインストール後設定を調整。`,
                        linksTag  : `linux-linux-archlabs-20190120-part3`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-archlabs-20190120-part3`
                    },
                    {
                        titleText : `一見シンプルなLinux教学 Linuxインストール manjaro linux 201606 kde`,
                        writeDate : `平成28年10月15日`,
                        version   : `v0.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/n6UjJXGJe9nAuJ`,
                        mainText  : `この記事は以前に書かれたもので、VirtualBoxでのManjaro Linuxのインストールと簡単なセットアップを目的としています。`,
                        linksTag  : `linux-manjaro-linux-201606-kde`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-manjaro-linux-201606-kde`,
                    },
                    {
                        titleText : `一見シンプルなLinux教学 linux mint cinnamon 18.1 操作設定`,
                        writeDate : `平成29年4月8日`,
                        version   : `v0.0.1`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/yhpyXyUr4WEo1x`,
                        mainText  : `この記事は Linux Mint Cinnamonをインストールした後のCinnamon設定機能の詳細な説明です。`,
                        linksTag  : `linux-linux-mint-cinnamon-181`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-mint-cinnamon-181`,
                    },
                    {
                        titleText : `一見シンプルなLinux教学 Linux CLI操作`,
                        writeDate : `平成28年11月26日`,
                        version   : `v0.0.3`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/iFW3qCxyy2ioQo`,
                        mainText  : `この記事は、Linuxターミナルの簡単な説明の最初のテキストであり、一般的な操作説明、w3mブラウザー、およびvimの簡単な説明が含まれています。`,
                        linksTag  : `linux-linux-cli`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-cli`,
                    },
                    {
                        titleText : `一見シンプルな教学 クレイジーからクレイジーまでのC言語Ex(一)`,
                        writeDate : `平成28年12月31日`,
                        version   : `v1.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/8dHHHpQHqyPaQG`,
                        mainText  : `この記事は、著者がC言語をクラッシュからクラッシュへと早期に書き直したものであり，CS弟子たちにISO 9899で策定されたC言語仕様を理解させ，基本的なC言語構文を作成することを目的としています。 `,
                        linksTag  : `cex-70564975`,
                        links     : `https://www.slideshare.net/ssuser6090c0/cex-70564975`,
                    },
                    {
                        titleText : `一見シンプルな教学 クレイジーからクレイジーまでのC言語Ex(二)`,
                        writeDate : `平成29年8月23日`,
                        version   : `v1.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/k2M84AlR73oWhP`,
                        mainText  : `この記事は、著者がC言語をクラッシュからクラッシュへと早期に書き直したものであり，CS弟子たちにISO 9899で策定されたC言語仕様を理解させ，高度なC言語構文の簡単な説明を次に示します。。 `,
                        linksTag  : `cex-79080568`,
                        links     : `https://www.slideshare.net/ssuser6090c0/cex-79080568`,
                    },
                    {
                        titleText : `FML Tool 教学`,
                        writeDate : `令和元年4月12日`,
                        writeDate : `2019-04-12`,
                        version   : `v1.4.6`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/gEuQPhd79jVHYl`,
                        mainText  : `ファジーマークアップ言語の説明。 この記事の目的は，このFML推論の簡単な紹介と，国立台南大学が提供するFML Lite（OASE）ツールでの遺伝的アルゴリズムの逆理論分析を行うことです。`,
                        linksTag  : `fml-tool`,
                        links     : `https://www.slideshare.net/ssuser6090c0/fml-tool`,
                    },
                    {
                        titleText : `一見シンプルなLinux教学  AndroidフォンでLinux(debian)を使用する方法`,
                        writeDate : `平成29年6月26日`,
                        version   : `v0.0.0`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/McYYXljYqB1HIB`,
                        mainText  : `Android上のGNUroot Debianソフトウェアについては，繁体字中国語の経験と操作手順を書いてください。`,
                        linksTag  : `linux-linux-77271842`,
                        links     : `https://www.slideshare.net/ssuser6090c0/linux-linux-77271842`,
                    },
                ]
            },
        }
    }),
});
