
const mainView = new Vue({
    el:"#mainView", 
    data:{
    },
    mounted() {
        this.$i18n.locale = 'zh-tw';
    },
    methods:{

    },
    i18n:new VueI18n({
        locale: 'zh-tw',
        fallbackLocale: 'zh-tw',
        messages:{
            "zh-tw": {
                hello         : `Hi, 歡迎來到這個網頁`,
                helloMeta     : `在這裡專門存放著我的作品集，包含我個人撰寫的文件與程式專案。`,
                about         : `個人資訊` ,
                name          : `Lian0123（連永立）`,
                skill         : `專長`,
                skillMeta     : `LinuxServer應用服務、人工智慧(Fuzzy部份)、全端網頁開發、Electron視窗應用開發`,
                seniority     : `資歷`,
                seniorityMeta : [`2016 國立臺南大學第九屆學生會新聞部部長`,`2017 國立臺南大學資訊工程學系第十屆宿營攝影長`,`2017 國立臺南大學資訊科學服務社 南化國小Scratch程式設計課講師`,`2018 國立臺南大學資訊科學服務社 南化國小Scratch程式設計課攝影`,`2019 參與下世代物聯網通訊技術虛擬實作工作坊`],
                sideProject   : `個人業餘專案`,
                projectMeta   : [`一個自定義C語言Macro，使語意流暢化的header檔。`,`在C++中使用像是Javascript自由的語法。`,`一個輔助Linux Mint Cinnamon系統安裝完後安裝其他常用程式的腳本。`,`純文字藝術。`,`使zhcorn能轉成UTF8繁體中文的小工具。`],
                writings      : `著作`,
                EasyLinux     : `看似比較簡單的Linux推坑教學`,
                EasyBase      : `看似比較簡單的推坑教學`,
                writingsMeta  : [`Linux安裝篇linux mint 18 cinnamon`,`Linux安裝篇 manjaro linux 201606 kde`,`C語言從崩潰到崩潰Ex(一)`,`C語言從崩潰到崩潰Ex(二)`,`linux mint cinnamon 18.1 操作設定教學`,`講解在手機上使用 linux`,`Linux安裝篇 ArchLabs 2019.01.20安裝`],
                links         : `相關連結`,
            },
            "zh-cn": {
                hello         : `Hi, 欢迎来到这个网页`,
                helloMeta     : `在这里专门存放着我的作品集，包含我个人撰写的文件与程式专案。`,
                about         : `个人资讯` ,
                name          : `Lian0123（连永立）`,
                skill         : `专長`,
                skillMeta     : `LinuxServer应用服务、人工智慧(Fuzzy部份)、全端网页开发、Electron视窗应用开发`,
                seniority     : `资历`,
                seniorityMeta : [`2016 国立台南大学第九届学生会新闻部部长`,`2017 国立台南大学资讯工程学系第十届宿营摄影长`,`2017 国立台南大学资讯科​​学服务社南化国小Scratch程式设计课讲师` ,`2018 国立台南大学资讯科​​学服务社南化国小Scratch程式设计课摄影`,`2019 参与下世代物联网通讯技术虚拟实作工作坊`],
                sideProject   : `个人业余专案`,
                projectMeta   : [`一个自定义C语言Macro，使语意流畅化的header档。`,`在C++中使用像是Javascript自由的语法。`,`一个辅助Linux Mint Cinnamon系统安装完后安装其他常用程式的脚本。`,`纯文字艺术。`,`使zhcorn能转成UTF8繁体中文的小工具。`],
                writings      : `著作`,
                EasyLinux     : `看似比较简单的Linux推坑教学`,
                EasyBase      : `看似比较简单的推坑教学`,
                writingsMeta  : [`Linux安装篇 linux mint 18 cinnamon`,`Linux安装篇 manjaro linux 201606 kde`,`C语言从崩溃到崩溃Ex(一)`,`C语言从崩溃到崩溃Ex(二)`,`linux mint cinnamon 18.1 操作设定教学`,`讲解在手机上使用linux`,`Linux安装篇ArchLabs 2019.01.20安装`],
                links         : `相关连结`,
            },
            "en": {
                hello         : `Hi, Welcome To This Website`,
                helloMeta     : `I store my portfolio in this page, including my personally written documents and program projects.`,
                about         : `About` ,
                name          : `Lian0123(Warren Lian)`,
                skill         : `Skill`,
                skillMeta     : `LinuxServer Application Services, AI(Fuzzy), Full-End Web Development, Electron Windows Application Development`,
                seniority     : `Seniority`,
                seniorityMeta : [`2016 Ninth Student Union of National Tainan University minister of information`,`2017 Tenth Camping Photography, Department of Information Engineering, National Tainan University`,`2017 National Tainan University Information Science Service Club, Nanhua Elementary School Scratch Program Design Class lecturer`,`2018 National Tainan University Information Science Service Club, Nanhua Elementary School Scratch Scratch Program Design Class photography`,`2019 Participate in the virtual reality workshop of next generation IoT communication technology`],
                sideProject   : `Side-Project`,
                projectMeta   : [`One Define the C language Macro，then make semantic helpful with header file.`,`Useing Javascript string type in C++.`,`A script to assist the installation of other common programs after the Linux Mint Cinnamon system is installed.`,`Only text art.`,`Turn Zhcorn into a UTF-8 Traditional Chinese tool.`],
                writings      : `Writings`,
                EasyLinux     : `See maybe simple Linux teaching`,
                EasyBase      : `See maybe simple teaching`,
                writingsMeta  : [`Linux installation chapter, linux mint 18 cinnamon`,`Linux installation chapter,manjaro linux 201606 kde`,`C language from crazy to crazy EX (1)`,`C language from crazy to crazy EX (2)`,`linux mint cinnamon 18.1 Setting`,`How to using linux(debian) in android phone`,`Linux installation chapter, ArchLabs 2019.01.20 install`],
                links         : `Related links`,
            },
            "jp": {
                hello         : `このページへようこそ`,
                helloMeta     : `個人的に作成した著作とProgram Projectsを含むポートフォリオをこのページに保存します。`,
                about         : `情報` ,
                name          : `Lian0123（立花 永蓮）`,
                skill         : `技術`,
                skillMeta     : `LinuxServerアプリケーション、人工知能（ファジー）、Full-End Web開発、Electronウィンドウアプリケーション開発`,
                seniority     : `経歴`,
                seniorityMeta : [`平成28年 国立台南大学第九屆学生会新聞部部長`,`平成29年 国立台南大学情報工学系第十屆キャンプ攝影`,`平成29年 国立台南大学情報科学服務部 南化国民小学Scratchプログラミングコース講師`,`平成30年 国立台南大学情報科学服務部 南化国民小学Scratchプログラミングコース攝影`,`令和元年 次世代のIoT通信技術の仮想ワークショップに参加する`],
                sideProject   : `Side-Project`,
                projectMeta   : [`C言語マクロを定義してから、ヘッダーファイルでセマンティックを役立てます。`,`C ++でJavaScriptのような構文を使用します。`,`Linux Mint Cinnamonシステムのインストール後、他の一般的なプログラムのインストールを支援するスクリプト。`,`テキストアート。`,`ZhcornをUTF-8繁体字ツールに変えることができます。`],
                writings      : `著作`,
                EasyLinux     : `一見シンプルなLinux教学`,
                EasyBase      : `一見シンプルな教学`,
                writingsMeta  : [`Linuxインストール linux mint 18 cinnamon`,`Linuxインストール manjaro linux 201606 kde`,`クレイジーからクレイジーまでのC言語Ex(一)`,`クレイジーからクレイジーまでのC言語Ex(二)`,`linux mint cinnamon 18.1 操作設定`,`AndroidフォンでLinux(debian)を使用する方法`,`Linuxインストール ArchLabs 2019.01.20インストール`],
                links         : `関連サイト`,
            },
        }
    }),
});
