
const projectView = new Vue({
    el:"#projectView", 
    data:{
    },
    mounted() {
        this.$i18n.locale = 'zh-tw';
    },
    methods:{

    },
    i18n:new VueI18n({
        locale: 'zh-tw',
        fallbackLocale: 'zh-tw',
        messages:{
            "zh-tw": {
                about:`介紹`,
                slideView:[
                    {
                        titleText : `E-Learning網站`,
                        writeDate : `2019-10-26`,
                        version   : `v0.0.0`,
                        langBase  : `go`,
                        type      : `image`,
                        frameName : `./Source/IMG/elearning.png`,
                        mainText  : `互動式教學設計，此專案為參與校園創新教學計畫之作品設計，在此為了提升服務的速度而使用go語言作為後端語言進行開發，並將一些操作設計為可平行化架構。`,
                        linksTag  : ``,
                        links     : ``,
                    },
                    {
                        titleText : `基於古典加密法中的替換密碼在音訊轉置到 bmp影像之欺騙偽造設計`,
                        writeDate : `2019-06-11`,
                        version   : `v1.2.0`,
                        langBase  : `JS`,
                        type      : `slideShare`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/Asem0f0rQmJYe8`,
                        mainText  : `一個把影像加密為BMP檔，並支援解密播放的播放器。並且在此可使用'無加密'、'線性加密'、'級數加密'、'弦波函數加密'、'亂數加密'等加密形式再次將加密資料轉在bmp檔的2進表示資料上，且同時在程式中也能將加密資料轉回到音訊檔的buffer上。`,
                        linksTag  : `Image-Audio-Player`,
                        links     : `https://github.com/Lian0123/Image-Audio-Player`,
                    },
                    {
                        titleText : `107-02-IOT-Project`,
                        writeDate : `2019-06-10`,
                        version   : `v0.0.0`,
                        langBase  : `js`,
                        type      : `image`,
                        frameName : `./Source/IMG/107-02-IOT-Project.png`,
                        mainText  : `物聯網課程期末專案，使用NB-IOT裝置擷取振動感測器的位置，並回傳到broker上，再傳到Server，最後由Web端以裝置ID為索引調閱資料回傳到網頁上，並計算其停止於某點的時間，以判斷是否需要協助。`,
                        linksTag  : `107-02-IOT-Project`,
                        links     : `https://github.com/Lian0123/107-02-IOT-Project`,
                    },
                    {
                        titleText : `教師Meeting預約系統`,
                        writeDate : `2019-01-09`,
                        version   : `v0.0.0`,
                        langBase  : `go`,
                        type      : `image`,
                        frameName : `./Source/IMG/Meeting.png`,
                        mainText  : `一個教師Meeting預約的系統，其目的用於給教師進行學生小組預約的管理。在此教師能建立課程與設定該課程可預約時段，除了對於需求方設定以1小時作為需求外，同時為了提供可設定每週固定時段，以減少教師重複的操作。但目前委託方似乎還沒將此系統投入實際使用。`,
                        linksTag  : ``,
                        links     : ``,
                    },
                    {
                        titleText : `twcall`,
                        writeDate : `2018-08-16`,
                        version   : `v0.0.0`,
                        langBase  : `bash`,
                        type      : `image`,
                        frameName : `./Source/IMG/twcall.png`,
                        mainText  : `對於zhcorn在現在的實體終端上的出現的編碼問題，最終發現其基於Big5編碼的問題造成的顯示錯誤，在此則做了簡單的調整上zhcorn能在實體終端上能正常顯示。`,
                        linksTag  : `twcall`,
                        links     : `https://github.com/Lian0123/twcall`,
                    },
                    {
                        titleText : `FMiCa-TW.sh`,
                        writeDate : `2018-07-28`,
                        version   : `v2.1.2`,
                        langBase  : `bash`,
                        type      : `slideShare`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/1cvYjWBDUqfvAt`,
                        mainText  : `這是個給 Linux Mint Cinnamon Taiwan 使用者的安裝程式用腳本，主要用於安裝其他軟體。其中囊括：18.1系列字體修正、更簡單的安裝其他主題、更方便的安裝瀏覽器與編輯器、'新krita的ppa而不用預設舊版的ppa等......。`,
                        linksTag  : `FMiCa-TW.sh`,
                        links     : `https://github.com/Lian0123/FMiCa-TW.sh`,
                    },
                    {
                        titleText : `Convolution Machine`,
                        writeDate : `2018-04-15`,
                        version   : `v0.0.0`,
                        langBase  : `js`,
                        type      : `image`,
                        frameName : `./Source/IMG/CM.png`,
                        mainText  : `訊號與系統課程專案，在此建立了一個簡單的語法分析與仿終端操作界面來實現捲積函數的計算，並使用c3.js來實現資料視覺化的表現，同時能將結果輸出成專有檔，且能讀檔。`,
                        linksTag  : `CM`,
                        links     : `https://github.com/Lian0123/CM`,
                    },
                ],
            },
            "zh-cn": {
                about:`介绍`,
                slideView:[
                    {
                        titleText : `E-Learning网站`,
                        writeDate : `2019-10-26`,
                        version   : `v0.0.0`,
                        langBase  : `go`,
                        type      : `image`,
                        frameName : `./Source/IMG/elearning.png`,
                        mainText  : `互动式教学设计，此专案为参与校园创新教学计画之作品设计，在此为了提升服务的速度而使用go语言作为后端语言进行开发，并将一些操作设计为可平行化架构。`,
                        linksTag  : ``,
                        links     : ``,
                    },
                    {
                        titleText : `基于古典加密法中的替换密码在音讯转置到 bmp影像之欺骗伪造设计`,
                        writeDate : `2019-06-11`,
                        version   : `v1.2.0`,
                        langBase  : `JS`,
                        type      : `slideShare`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/Asem0f0rQmJYe8`,
                        mainText  : `一个把影像加密为BMP档，并支援解密播放的播放器。并且在此可使用'无加密'、'线性加密'、'级数加密'、'弦波函数加密'、'乱数加密'等加密形式再次将加密资料转在bmp档的2进表示资料上，且同时在程式中也能将加密资料转回到音讯档的buffer上。`,
                        linksTag  : `Image-Audio-Player`,
                        links     : `https://github.com/Lian0123/Image-Audio-Player`,
                    },
                    {
                        titleText : `107-02-IOT-Project`,
                        writeDate : `2019-06-10`,
                        version   : `v0.0.0`,
                        langBase  : `js`,
                        type      : `image`,
                        frameName : `./Source/IMG/107-02-IOT-Project.png`,
                        mainText  : `物联网课程期末专案，使用NB-IOT装置撷取振动感测器的位置，并回传到broker上，再传到Server，最后由Web端以装置ID为索引调阅资料回传到网页上，并计算其停止于某点的时间，以判断是否需要协助。`,
                        linksTag  : `107-02-IOT-Project`,
                        links     : `https://github.com/Lian0123/107-02-IOT-Project`,
                    },
                    {
                        titleText : `教师Meeting预约系统`,
                        writeDate : `2019-01-09`,
                        version   : `v0.0.0`,
                        langBase  : `go`,
                        type      : `image`,
                        frameName : `./Source/IMG/Meeting.png`,
                        mainText  : `一个教师Meeting预约的系统，其目的用于给教师进行学生小组预约的管理。在此教师能建立课程与设定该课程可预约时段，除了对于需求方设定以1小时作为需求外，同时为了提供可设定每周固定时段，以减少教师重复的操作。但目前委托方似乎还没将此系统投入实际使用。`,
                        linksTag  : ``,
                        links     : ``,
                    },
                    {
                        titleText : `twcall`,
                        writeDate : `2018-08-16`,
                        version   : `v0.0.0`,
                        langBase  : `bash`,
                        type      : `image`,
                        frameName : `./Source/IMG/twcall.png`,
                        mainText  : `对于zhcorn在现在的实体终端上的出现的编码问题，最终发现其基于Big5编码的问题造成的显示错误，在此则做了简单的调整上zhcorn能在实体终端上能正常显示。`,
                        linksTag  : `twcall`,
                        links     : `https://github.com/Lian0123/twcall`,
                    },
                    {
                        titleText : `FMiCa-TW.sh`,
                        writeDate : `2018-07-28`,
                        version   : `v2.1.2`,
                        langBase  : `bash`,
                        type      : `slideShare`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/1cvYjWBDUqfvAt`,
                        mainText  : `这是个给 Linux Mint Cinnamon Taiwan 使用者的安装程式用脚本，主要用于安装其他软体。其中囊括：18.1系列字体修正、更简单的安装其他主题、更方便的安装浏览器与编辑器、'新krita的ppa而不用预设旧版的ppa等......。`,
                        linksTag  : `FMiCa-TW.sh`,
                        links     : `https://github.com/Lian0123/FMiCa-TW.sh`,
                    },
                    {
                        titleText : `Convolution Machine`,
                        writeDate : `2018-04-15`,
                        version   : `v0.0.0`,
                        langBase  : `js`,
                        type      : `image`,
                        frameName : `./Source/IMG/CM.png`,
                        mainText  : `讯号与系统课程专案，在此建立了一个简单的语法分析与仿终端操作界面来实现卷积函数的计算，并使用c3.js来实现资料视觉化的表现，同时能将结果输出成专有档，且能读档。`,
                        linksTag  : `CM`,
                        links     : `https://github.com/Lian0123/CM`,
                    },

                ]
            },
            "en": {
                about:`Introduction`,
                slideView:[
                    
                    {
                        titleText : `E-Learning Web`,
                        writeDate : `2019-10-26`,
                        version   : `v0.0.0`,
                        langBase  : `go`,
                        type      : `image`,
                        frameName : `./Source/IMG/elearning.png`,
                        mainText  : `Interactive instructional design, this project is design for Innovative Campus Teaching Program, There using go language to end-web language to design, and planning for Parallelizable architecture.`,
                        linksTag  : ``,
                        links     : ``,
                    },
                    {
                        titleText : `Image-Audio-Player`,
                        writeDate : `2019-06-11`,
                        version   : `v1.2.0`,
                        langBase  : `JS`,
                        type      : `slideShare`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/Asem0f0rQmJYe8`,
                        mainText  : `A player that encrypts images into BMP files and supports decryption playback. There can using 'No encryption','linear funciton encryption','series funciton encryption','wave funciton encryption','random encryption' to encryption data to bmp file binary data, and there can also decryption data to audio buffer play.`,
                        linksTag  : `Image-Audio-Player`,
                        links     : `https://github.com/Lian0123/Image-Audio-Player`,
                    },
                    {
                        titleText : `107-02-IOT-Project`,
                        writeDate : `2019-06-10`,
                        version   : `v0.0.0`,
                        langBase  : `js`,
                        type      : `image`,
                        frameName : `./Source/IMG/107-02-IOT-Project.png`,
                        mainText  : `IOT course project, using NB-IOT to read sensor location, and post to broker, next post to server. Finally, the web uses the device ID as the index to get data return to web page, and computing stop time for condition, people need to help.`,
                        linksTag  : `107-02-IOT-Project`,
                        links     : `https://github.com/Lian0123/107-02-IOT-Project`,
                    },
                    {
                        titleText : `Teacher Meeting System`,
                        writeDate : `2019-01-09`,
                        version   : `v0.0.0`,
                        langBase  : `go`,
                        type      : `image`,
                        frameName : `./Source/IMG/Meeting.png`,
                        mainText  : `A school teacher Meeting system, using for student group make an appointment in teacher class. Teacher can make a new time for student group reserve, and one hour one group. At the same time, in order to provide a fixed weekly time period to reduce the repeated operations of teachers. But customers do not seem to have put this system into practical use yet.`,
                        linksTag  : ``,
                        links     : ``,
                    },
                    {
                        titleText : `twcall`,
                        writeDate : `2018-08-16`,
                        version   : `v0.0.0`,
                        langBase  : `bash`,
                        type      : `image`,
                        frameName : `./Source/IMG/twcall.png`,
                        mainText  : `Regarding the encoding problem that zhcorn appeared on the current physical terminal, I finally found a display error caused by the problem based on Big5 encoding. Here, I made a simple adjustment to make zhcorn display properly on the physical terminal.`,
                        linksTag  : `twcall`,
                        links     : `https://github.com/Lian0123/twcall`,
                    },
                    {
                        titleText : `FMiCa-TW.sh`,
                        writeDate : `2018-07-28`,
                        version   : `v2.1.2`,
                        langBase  : `bash`,
                        type      : `slideShare`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/1cvYjWBDUqfvAt`,
                        mainText  : `This is for Linux Mint Cinnamon Taiwan user install shell script，for install some software. There have：change 18.1 chinese font for other, eazy install some theme, easy install browser and text-editer......`,
                        linksTag  : `FMiCa-TW.sh`,
                        links     : `https://github.com/Lian0123/FMiCa-TW.sh`,
                    },
                    {
                        titleText : `Convolution Machine`,
                        writeDate : `2018-04-15`,
                        version   : `v0.0.0`,
                        langBase  : `js`,
                        type      : `image`,
                        frameName : `./Source/IMG/CM.png`,
                        mainText  : `Signals and systems course project, there design a easy parsing and terminal to computing convolution function, and using c3.js to show input and output, also can save file and load file.`,
                        linksTag  : `CM`,
                        links     : `https://github.com/Lian0123/CM`,
                    },
                ]
            },
            "jp": {
                about:`紹介`,
                slideView:[
                    {
                        titleText : `E-Learning ウェブサイト`,
                        writeDate : `令和元年10月26日`,
                        version   : `v0.0.0`,
                        langBase  : `go`,
                        type      : `image`,
                        frameName : `./Source/IMG/elearning.png`,
                        mainText  : `互動式教學設計，此專案為參與校園創新教學計畫之作品設計，在此為了提升服務的速度而使用go語言作為後端語言進行開發，並將一些操作設計為可平行化架構。`,
                        linksTag  : ``,
                        links     : ``,
                    },
                    {
                        titleText : `Image-Audio-Player`,
                        writeDate : `令和元年6月11日`,
                        version   : `v1.2.0`,
                        langBase  : `JS`,
                        type      : `slideShare`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/Asem0f0rQmJYe8`,
                        mainText  : `一個把影像加密為BMP檔，並支援解密播放的播放器。並且在此可使用'無加密'、'線性加密'、'級數加密'、'弦波函數加密'、'亂數加密'等加密形式再次將加密資料轉在bmp檔的2進表示資料上，且同時在程式中也能將加密資料轉回到音訊檔的buffer上。`,
                        linksTag  : `Image-Audio-Player`,
                        links     : `https://github.com/Lian0123/Image-Audio-Player`,
                    },
                    {
                        titleText : `107-02-IOT-Project`,
                        writeDate : `令和元年6月10日`,
                        version   : `v0.0.0`,
                        langBase  : `js`,
                        type      : `image`,
                        frameName : `./Source/IMG/107-02-IOT-Project.png`,
                        mainText  : `物聯網課程期末專案，使用NB-IOT裝置擷取振動感測器的位置，並回傳到broker上，再傳到Server，最後由Web端以裝置ID為索引調閱資料回傳到網頁上，並計算其停止於某點的時間，以判斷是否需要協助。`,
                        linksTag  : `107-02-IOT-Project`,
                        links     : `https://github.com/Lian0123/107-02-IOT-Project`,
                    },
                    {
                        titleText : `先生 Meeting予約システム`,
                        writeDate : `平成31年1月19日`,
                        version   : `v0.0.0`,
                        langBase  : `go`,
                        type      : `image`,
                        frameName : `./Source/IMG/Meeting.png`,
                        mainText  : `一個教師Meeting預約的系統，其目的用於給教師進行學生小組預約的管理。在此教師能建立課程與設定該課程可預約時段，除了對於需求方設定以1小時作為需求外，同時為了提供可設定每週固定時段，以減少教師重複的操作。但目前委託方似乎還沒將此系統投入實際使用。`,
                        linksTag  : ``,
                        links     : ``,
                    },
                    {
                        titleText : `twcall`,
                        writeDate : `平成30年8月16日`,
                        version   : `v0.0.0`,
                        langBase  : `bash`,
                        type      : `image`,
                        frameName : `./Source/IMG/twcall.png`,
                        mainText  : `對於zhcorn在現在的實體終端上的出現的編碼問題，最終發現其基於Big5編碼的問題造成的顯示錯誤，在此則做了簡單的調整上zhcorn能在實體終端上能正常顯示。`,
                        linksTag  : `twcall`,
                        links     : `https://github.com/Lian0123/twcall`,
                    },
                    {
                        titleText : `FMiCa-TW.sh`,
                        writeDate : `平成30年7月28日`,
                        version   : `v2.1.2`,
                        langBase  : `bash`,
                        type      : `slideShare`,
                        frameName : `https://www.slideshare.net/slideshow/embed_code/key/1cvYjWBDUqfvAt`,
                        mainText  : `這是個給 Linux Mint Cinnamon Taiwan 使用者的安裝程式用腳本，主要用於安裝其他軟體。其中囊括：18.1系列字體修正、更簡單的安裝其他主題、更方便的安裝瀏覽器與編輯器、'新krita的ppa而不用預設舊版的ppa等......。`,
                        linksTag  : `FMiCa-TW.sh`,
                        links     : `https://github.com/Lian0123/FMiCa-TW.sh`,
                    },
                    {
                        titleText : `Convolution Machine`,
                        writeDate : `平成30年4月15日`,
                        version   : `v0.0.0`,
                        langBase  : `js`,
                        type      : `image`,
                        frameName : `./Source/IMG/CM.png`,
                        mainText  : `訊號與系統課程專案，在此建立了一個簡單的語法分析與仿終端操作界面來實現捲積函數的計算，並使用c3.js來實現資料視覺化的表現，同時能將結果輸出成專有檔，且能讀檔。`,
                        linksTag  : `CM`,
                        links     : `https://github.com/Lian0123/CM`,
                    },
                ]
            }
        },
    }),
});